- Frontend/app/src/components/LoginPage.tsx
- Frontend/app/src/components/SignUpPage.tsx
- Frontend/app/src/components/style/LoginPage.css
I am merging the master branch to the chat room to make the code base in the other branch up to date and ready for further changes.
> Merge and sync codebase 

- Frontend/app/src/components/style/LoginPage.css
I want to sync to code base to be up to date.
> Sync code base 

- Backend/api/APIDocumentation.md
- Backend/api/index.js
> Merge codebase

- .VSCodeCounter/2021-11-27_20-03-28/details.md
- .VSCodeCounter/2021-11-27_20-03-28/results.csv
- .VSCodeCounter/2021-11-27_20-03-28/results.md
- .VSCodeCounter/2021-11-27_20-03-28/results.txt
- Backend/api/index.js
- Backend/socket/index.js
- Backend/socket/messageSchema.js
- Frontend/app/src/components/ChatBubble.tsx
- Frontend/app/src/components/ChatRoom.tsx
- Frontend/app/src/components/ExecuteButton.tsx
- Frontend/app/src/components/Message.tsx
- Frontend/app/src/components/UserBar.tsx
- Frontend/app/src/components/VerifyCheckMark.tsx
- Frontend/app/src/components/style/Message.css
- Frontend/app/src/components/style/VerifyCheckMark.css
- Frontend/app/src/scripts/apiRequest.ts
- Frontend/app/src/scripts/askNotify.ts
- Frontend/app/src/scripts/badWords.ts
- Frontend/app/src/scripts/findUserInfo.ts
- Frontend/app/src/scripts/login.ts
- Frontend/app/src/scripts/notify.ts
- Frontend/app/src/scripts/send.ts
- Frontend/app/src/scripts/signUp.ts
- Frontend/app/src/scripts/types.ts
I am trying to merge a PR to the master codebase and I want to release the v1.2lts stable by the end of this week this PR includes the verify checkmark as well as some bug fixes.
Thanks Alvin.
> Chat room merge version 1.2lts

- Frontend/app/src/components/SignUpPage.tsx
- Frontend/app/src/components/style/ChatRoom.css
- Frontend/app/src/components/style/ExecuteButton.css
- Frontend/app/src/components/style/LoginForm.css
- Frontend/app/src/components/style/Signup.css
Today I have fixed some login and sign up page style bugs like:
- Mobile responsive bugs
- Color corrections 
- Squashed buttons
Thanks!
> Fix login&sign up styles bugs

- Frontend/app/src/components/style/UserBar.css
I have aligned the user list to the center in this branch, previously it was using a padding and an absolute value. Now it's using CSS grid layout.
Thanks!
> Center align user list

- Frontend/app/src/components/VerifyCheckMark.tsx
I have done some formatting changes in the frontend code and now I will be merging it into the main codebase.
Thanks!
> Formatting changes

- .gitignore
- Frontend/.expo/README.md
- Frontend/.expo/packager-info.json
- Frontend/.expo/settings.json
There was nothing to be done in this branch the backend seems fine and good.
thanks!
> Backend fixes - nothing was done!

- Frontend/assets/fonts/loader.ts
- Frontend/src/Router.tsx
Here is the bug fix for the font loading issue in the issues tab.
Thanks!
> Font not loading correctly bug fix

- mobile/src/components/Icon.tsx
- mobile/src/screens/Information.tsx
- mobile/src/screens/Login.tsx
- mobile/src/screens/Signup.tsx
- mobile/src/scripts/getUser.ts
This fix includes the fix for signup bug and more bug fixes to see full change lob please see the commit tab.
Thanks!
> Security fixes

- mobile/src/screens/CreateRoom.tsx
- mobile/src/screens/Login.tsx
- mobile/src/scripts/createRoom.ts
> Security fix

- api/src/endpoints/SearchMessage.ts
- mobile/src/Router.tsx
- mobile/src/components/Button.tsx
- mobile/src/components/Form.tsx
- mobile/src/components/Icon.tsx
- mobile/src/components/LoginForm.tsx
- mobile/src/components/RoomList.tsx
- mobile/src/redux/index.ts
- mobile/src/screens/AddRoom.tsx
- mobile/src/screens/BlockError.tsx
- mobile/src/screens/Chat.tsx
- mobile/src/screens/CreateRoom.tsx
- mobile/src/screens/Error.tsx
- mobile/src/screens/Menu.tsx
- mobile/src/screens/SignoutConfirm.tsx
- mobile/src/scripts/api.ts
- mobile/src/scripts/createRoom.ts
- mobile/src/scripts/getMessages.ts
- mobile/src/scripts/getRooms.ts
- mobile/src/scripts/getUser.ts
- mobile/src/scripts/index.d.ts
- mobile/src/scripts/joinRoom.ts
- mobile/src/scripts/login.ts
- mobile/src/scripts/signup.ts
Hi have some formatting fixes ready to be merged into the master branch
Thanks!
> Formatting fixes

- package.json
- src/components/Icon.tsx
- src/components/RoomList.tsx
- src/screens/Menu.tsx
- src/screens/RoomInformation.tsx
- yarn.lock
Hi, I have created a copy id feature for Chill&chat and also added some icons to make it look better. There were also some small style changes here and there, to see all changes please check the commit tab.
Thanks! 🙏 
Regards, Alvin.
> Feature: copy room id

- src/components/Button.tsx
- src/components/ChatRoomBar.tsx
- src/components/Form.tsx
- src/components/Icon.tsx
- src/components/LoginForm.tsx
- src/components/Message.tsx
- src/components/RoomList.tsx
- src/redux/action.ts
- src/redux/index.d.ts
- src/redux/reducers/userInfo.ts
- src/screens/Login.tsx
- src/scripts/sendMessage.ts
Here is some fixes and changes to the codebase
> House keeping tasks 

- package.json
- src/components/Message.tsx
- src/components/index.d.ts
- src/screens/AddRoom.tsx
- src/screens/Chat.tsx
- src/screens/CreateRoom.tsx
- src/screens/Menu.tsx
- src/scripts/api.ts
- src/scripts/getRooms.ts
- src/scripts/getUserWithId.ts
- src/scripts/index.d.ts
- yarn.lock
I have done a chat room update, this update will get the user data and make icons available for messages. 
Thanks! 
Regards Alvin.
> Chat room update WIP

- src/components/Form.tsx
- src/components/index.d.ts
- src/screens/Menu.tsx
- src/scripts/index.d.ts
- src/scripts/signup.ts
Hello, I have prepared the menu search feature where you could search for your room. There's not much to it so yeah!
Thanks!
> Menu search 

- src/screens/RoomDangerZone.tsx
- src/scripts/reportRoom.ts
This is the pull request for the report room endpoint. As mentioned in the issue
> 70 update frontend script to support report room endpoint

- src/screens/UpdateIconColor.tsx
I have refactored the code in the ```UpdateIconColor``` component, which underwent an untracked update requiring a  refactoring effort. Specifically, I have changed the styles from an embedded form into the styling variable in this ticket, like this code snippet below.
From this
```js
return(
<View style={{container:{flex:1, height: 100}}></View>
);
```
To this
```js
const style = StyleSheet.create({container:{flex:1, height: 100}});
return(
<View style={style.container}></View>
);
```
Thanks
> 72 refactoring ticket

- src/components/RoomList.tsx
- src/components/index.d.ts
- src/screens/Menu.tsx
This is the show new messages feature pull request, this feature allows users to see the most recent message from the selected room.
> 73 show new messages feature

- src/components/RoomWelcomer.tsx
- src/screens/Chat.tsx
I have created a ```RoomWelcomer``` component in ```/src/components/RoomWelcomer.tsx``` and have successfully implemented it into the ```Chat``` screen, which is in ```/src/screen/Chat.tsx``` The ```RoomWelcomer``` component will be rendered at the beginning of the ```ScrollView``` component that will be the first thing a new user sees
> 76 room welcome screen

- src/screens/Login.tsx
- src/screens/Signup.tsx
I have fixed Apple review issue by adding a loading spinner to the ```signup``` and ```login``` screens. This will tell the user that the system is not responding and prevents overloads.
> 82 apple review issue

- app.config.js
- src/Router.tsx
- src/screens/ImageBase.tsx
- src/screens/SendImage.tsx
- src/scripts/api.ts
- src/scripts/getGif.ts
- src/scripts/index.d.ts
Hello!
This is the pull request for the gif support feature to be implemented in the ```sendImage``` page. All request of the feature is now met. The gif feature works by fetching data from the GIPHY API and placing it on the screen, once the user clicks a gif, the gif will be transferred by redux to the send image page where it can be processed. We are using the old architecture of the redux state from last year.
More info: #77
> 77 giphyr api for gif support

- src/screens/Login.tsx
- src/screens/Menu.tsx
- src/screens/MessageOptions.tsx
- yarn.lock
Hello!
This is the pull request with all the progress for the housekeeping code form #87. This pull request is now ready for review and merge
More information regarding the specific bugs and improvements can be found in the commit logs below or in #87 
Thanks for reading!!!
> 87 housekeeping

- src/components/Icon.tsx
- src/components/Message.tsx
- src/components/RoomList.tsx
- src/components/TypingAnimation.tsx
- src/screens/Chat.tsx
- src/screens/Information.tsx
- src/screens/Menu.tsx
- src/screens/RoomId.tsx
- src/screens/RoomInformation.tsx
- src/screens/SendImage.tsx
- src/screens/UserMenu.tsx
- src/screens/UserProfile.tsx
- src/scripts/api.ts
- src/scripts/deleteMessage.ts
- src/scripts/filter.ts
- src/scripts/index.d.ts
- src/scripts/sendMessage.ts
- src/scripts/setKeyboardSocket.ts
- src/scripts/uploadContent.ts
- src/scripts/verifyClient.ts
Hello!
Welcome to the 1.15.1 housekeeping branch, this is where all the changes for version 1.15.1 will be. Here is a full list of changes made and to be made:
Some styles in the ```SendImage```, ```Menu```, and ```Icon``` screens and components.
These style changes will make the UI look more modern and clean for a more robust and better user experience.
A new feature was requested to have all messages to be allowed to be shared with other rooms, instead of copy and pasting, this button will be added to the ```MessageOptions``` screen and will guide the use to another page for more sharing options.
More feature and bug-fix request tickets can be posted right here!
Thank you!
> House keeping 1.15.1

- app.config.js
- package.json
- src/screens/Menu.tsx
- src/screens/registerPushNotificationToken.js
- src/scripts/api.ts
- src/scripts/index.d.ts
- src/scripts/uploadToken.ts
- yarn.lock
Hello, I have added some new code that will handle the notifications on Chill&chat, the notifications should be working once the API version with the notifications is up and running. 
Please review soon.
Thanks!
> 1.16.0 new features

- src/Router.tsx
- src/components/ChatRoomBar.tsx
- src/screens/CreateRoom.tsx
- src/screens/JoinRoom.tsx
- src/screens/Login.tsx
- src/screens/PublicRooms.tsx
- src/screens/RoomDangerZone.tsx
Hello there everyone!
This is a follow-up pull request for issue #98 with the runtime error regarding navigation issues. In this pull request, I have completely tested and fixed this warning message by changing and re-routing some navigational paths. Please note that this pull request is now ready for review and merge into the new 1.16.1 branch which was mentioned here: #96
Thank you!
> Fixed navigation warning by renaming navigation path
